Added name reacts to greeting_amnesia
Monika-After-Story/MonikaModDev pull request #6229
Opened 2020-08-25 17:10 UTC by fromulus

For consistency for the other name input topics, and because I thought it'd be cute.

2020-08-25 19:01 UTC, Booplicate requested changes

2020-08-25 19:01 UTC, Booplicate commented on Monika After Story/game/script-greetings.rpy
> +    $ fakename = renpy.input('What is your name?',length=15).strip(' \t\n\r')
```suggestion
    $ fakename = renpy.input("What is your name?", length=20).strip(" \t\n\r")
```

2020-09-26 21:57 UTC, Booplicate requested changes

2020-09-26 21:57 UTC, Booplicate commented on Monika After Story/game/script-greetings.rpy
>      m 1eub "My name is Monika."
I don't like how she tells us her name, and then stays with open mouth.
```suggestion
    m 1eub "My name is Monika."
    
    show monika 1eua zorder MAS_MONIKA_Z
```

2020-09-26 21:57 UTC, Booplicate commented on Monika After Story/game/script-greetings.rpy
> +    extend 1rksdlc "[end_of_line]."
Don't need this period here.
```suggestion
    extend 1rksdlc "[end_of_line]"
```

2020-09-26 22:09 UTC, jmwall24 approved these changes

2020-09-26 22:14 UTC, Booplicate approved these changes
hope

2020-09-26 22:15 UTC, multimokia approved these changes
[Hope Runs Deep](https://www.youtube.com/watch?v=L6BCj1Yesvc)

2020-09-26 22:16 UTC, merged