More kiss quips
Monika-After-Story/MonikaModDev pull request #6357
Opened 2020-09-19 03:38 UTC by scpketer

Some more may still fit in, working on it.

2020-09-20 11:21 UTC, Ravenclaw-OIer requested changes
I don't really like this PR, I think that this makes Monika a little bit *too* annoying.

Especially the *It felt so good* part. Really.

2020-09-20 11:26 UTC, scpketer commented
Roger that.

2020-09-26 20:49 UTC, multimokia approved these changes

2020-09-26 21:08 UTC, jmwall24 approved these changes

2020-09-26 21:08 UTC, merged