Improvement/wiki brackets drop
Monika-After-Story/MonikaModDev pull request #6417
Opened 2020-09-29 16:24 UTC by scpketer

According to [the Wikipedia article naming conventions](https://en.wikipedia.org/wiki/Wikipedia:Article_titles), round brackets (parentheses) are supposed to clarify or disambiguate articles.

Changes made in the branch involved in this PR remove trailing parentheses from the article name in window reaction.

2020-10-05 17:27 UTC, multimokia requested changes

2020-10-05 17:27 UTC, multimokia commented on Monika After Story/game/zz_windowreacts.rpy
> +        import re
No need to `import re` here. It's already initialized well in advance at init 0.
```suggestion
```

2020-10-05 17:27 UTC, multimokia commented on Monika After Story/game/zz_windowreacts.rpy
> +            #Now we get the article
```suggestion
            #Now we get the article
```

2020-10-05 17:35 UTC, multimokia approved these changes

2020-11-08 02:08 UTC, ThePotatoGuy approved these changes

2020-11-08 02:08 UTC, merged