Strawberry - By Paul Baribeau
Monika-After-Story/MonikaModDev pull request #6460
Opened 2020-10-05 01:46 UTC by StayHappy1270

ok i did it first project!

2020-10-16 03:12 UTC, Rai99 commented on Monika After Story/game/script-songs.rpy
> +    m 5dkbsa "But for now{w=0.3} I geuss I can just continue to day dream about all the adventures we'll have together one day."
```suggestion
    m 5dkbsa "But for now{w=0.3} I guess I can just continue to daydream about all the adventures we'll have together one day."
```

2020-10-16 03:12 UTC, Rai99 commented on Monika After Story/game/script-songs.rpy
> +    m 5ekbsu "I can't wait till the day I can finally be with you, [player]."
Dissolve into body pose 5.

2020-10-16 03:12 UTC, Rai99 commented on Monika After Story/game/script-songs.rpy
> +    m 5hsbsb "{cps=26}And I would love to find you...{/cps}"
Dissolve into body pose 5.

2020-10-16 03:12 UTC, Rai99 commented on Monika After Story/game/script-songs.rpy
> +    m 2dsbsb "{cps=28}I would make a bas{w=0.1}ket with the front {w=0.3} of my t-shirt,{/cps}"
Dissolve out of body pose 5.

2020-10-16 03:12 UTC, Rai99 commented on Monika After Story/game/script-songs.rpy
> +    m 2hubfa "Ah~ I can't wait untill the day we'll finally get to see that happen!"
Dissolve out of body pose 5.
```suggestion
    m 2hubfa "Ah~ I can't wait until the day we'll finally get to see that happen!"
```

2020-10-16 03:12 UTC, Rai99 commented on Monika After Story/game/script-songs.rpy
> +    m 5hsbsb "{cps=26}And I would love to find you...{/cps}"
Dissolve into body pose 5.

2020-10-16 03:12 UTC, Rai99 commented on Monika After Story/game/script-songs.rpy
> +    m 5rsbfb "{cps=26}Standing ankle{w=0.3} deep in a tide pool...{/cps}"
Dissolve into and out of body pose 5.

2020-10-16 03:12 UTC, Rai99 commented on Monika After Story/game/script-songs.rpy
> +    m 2dsbsb "{cps=28}I would make a bas{w=0.1}ket with the front {w=0.3} of my t-shirt,{/cps}"
Dissolve out of body pose 5.

2020-10-16 03:12 UTC, Rai99 commented on Monika After Story/game/script-songs.rpy
> +    m 5rsbsa "{cps=26}Lying down on my front lawn...{/cps}"
Dissolve into body pose 5.

2020-10-16 03:12 UTC, Rai99 commented on Monika After Story/game/script-songs.rpy
> +    m 2hsbsu "..."
Dissolve out of body pose 5.

2020-11-25 04:13 UTC, StayHappy1270 commented on Monika After Story/game/script-songs.rpy
> +    m 5hsbsb "{cps=26}And I would love to find you...{/cps}"
`dfgbh`

2020-11-25 04:30 UTC, StayHappy1270 commented on Monika After Story/game/script-songs.rpy
> +    extend 2dkbsa "{w=0.3} That are sharp,{w=0.3} and tart,{w=0.3} and red,{w=0.3} and deep...{/cps}"
```suggestion
    extend 2dkbsa "{w=0.3} That are sharp,{w=0.3} and tart,{w=0.3} and red,{w=0.3} and deep...{/cps}"
    show monika 2dkbsa at t11 zorder MAS_MONIKA_Z with dissolve_monika

2020-11-25 04:30 UTC, StayHappy1270 commented on Monika After Story/game/script-songs.rpy
> +    extend 5lsbsb "{cps=26} Growing wild out by the woods~{/cps}"
```suggestion
    extend 5lsbsb "{cps=26} Growing wild out by the woods~{/cps}"
    show monika 5lsbsb at t11 zorder MAS_MONIKA_Z with dissolve_monika
```

2020-11-25 04:30 UTC, StayHappy1270 commented on Monika After Story/game/script-songs.rpy
> +    m 2hsbsu "..."
```suggestion
    m 2hsbsu "..."
    show monika 2hsbsu at t11 zorder MAS_MONIKA_Z with dissolve_monika

2020-11-25 04:30 UTC, StayHappy1270 commented on Monika After Story/game/script-songs.rpy
> +    m 5tsbfb "And finally get to look back into your eyes..."
```suggestion
    m 5tsbfb "And finally get to look back into your eyes..."
    show monika 5tsbfb at t11 zorder MAS_MONIKA_Z with dissolve_monika
```

2020-11-25 04:30 UTC, StayHappy1270 commented on Monika After Story/game/script-songs.rpy
> +    extend 2dkbsa "{w=0.3} That are sharp,{w=0.3} and tart,{w=0.3} and red,{w=0.3} and deep...{/cps}"
```suggestion
    extend 2dkbsa "{w=0.3} That are sharp,{w=0.3} and tart,{w=0.3} and red,{w=0.3} and deep...{/cps}"
    show monika 2dkbsa at t11 zorder MAS_MONIKA_Z  with dissolve_monika
```

2020-11-25 04:30 UTC, StayHappy1270 commented on Monika After Story/game/script-songs.rpy
> +    extend 5lsbsb "{cps=26} Growing wild out by the woods~{/cps}"
```suggestion
    extend 5lsbsb "{cps=26} Growing wild out by the woods~{/cps}"
    show monika 5lsbsb at t11 zorder MAS_MONIKA_Z  with dissolve_monika
```

2020-11-25 04:30 UTC, StayHappy1270 commented on Monika After Story/game/script-songs.rpy
> +    extend 3hubsa "{cps=26}With my tennis shoes off!~{/cps}"
```suggestion
    extend 3hubsa "{cps=26}With my tennis shoes off!~{/cps}"
    show monika 3hubsa at t11 zorder MAS_MONIKA_Z with dissolve_monika
```

2020-11-25 04:30 UTC, StayHappy1270 commented on Monika After Story/game/script-songs.rpy
> +    m 5rsbfb "{cps=26}Standing ankle{w=0.3} deep in a tide pool...{/cps}"
```suggestion
    m 5rsbfb "{cps=26}Standing ankle{w=0.3} deep in a tide pool...{/cps}"
    show monika 5rsbfb at t11 zorder MAS_MONIKA_Z with dissolve_monika
```

2020-11-25 04:30 UTC, StayHappy1270 commented on Monika After Story/game/script-songs.rpy
> +    m 2dubsb "{cps=26}And I want to look at you...{/cps}"
```suggestion
    m 2dubsb "{cps=26}And I want to look at you...{/cps}"
    show monika 2dubsb at t11 zorder MAS_MONIKA_Z with dissolve_monika
```

2020-11-25 04:30 UTC, StayHappy1270 commented on Monika After Story/game/script-songs.rpy
> +    m 5dsbsb "{cps=26}But you just go {i}on and on and on~{/i}{/cps}"
```suggestion
    m 5dsbsb "{cps=26}But you just go {i}on and on and on~{/i}{/cps}"
    show monika 5dsbsb at t11 zorder MAS_MONIKA_Z with dissolve_monika
```

2020-11-25 04:35 UTC, StayHappy1270 commented
yaaay i finally had time to add in all the fades and is good 2 go!

2021-04-22 20:15 UTC, Booplicate requested changes

2021-04-22 20:15 UTC, Booplicate commented on Monika After Story/game/script-songs.rpy
> +            random=True,
```suggestion
```

2021-04-22 20:15 UTC, Booplicate commented on Monika After Story/game/script-songs.rpy
> +    m 3dud "{i}{cps=26}~Because the ocean is filled with all kinds of colors~{/i}"
```suggestion
    m 3dud "{i}{cps=26}~Because the ocean is filled with all kinds of colors~{/cps}{/i}"
```

2021-04-27 17:02 UTC, multimokia approved these changes

2021-04-27 17:19 UTC, StayHappy1270 reviewed
Im confused i reviewed/ approved all these changes but it still says there are change requests I need to review

2021-04-27 20:52 UTC, jmwall24 submitted a review, later dismissed

2021-04-27 21:37 UTC, jmwall24 commented
> Im confused i reviewed/ approved all these changes but it still says there are change requests I need to review
You're fine @StayHappy1270 it says that until everyone that reqt changes approves the PR.

2021-04-27 21:50 UTC, Booplicate approved these changes
🍓

2021-04-27 21:55 UTC, multimokia approved these changes
![image](https://user-images.githubusercontent.com/22531674/116317742-c012a800-a781-11eb-9e49-b0a2c4ee307b.png)

2021-04-27 22:01 UTC, jmwall24 approved these changes

2021-04-27 22:02 UTC, merged