New-O31
Monika-After-Story/MonikaModDev pull request #6556
Opened 2020-10-25 17:14 UTC by multimokia

# New O31

## :crab: RIN IS FIXED 🦀 
### New ACS (NOTE: These are NOT selectable):
- `mas_acs_rin_bows_front`
- `mas_acs_rin_bows_back`
- `mas_acs_rin_ears`

## TODO:
- [ ] o31 cleanup in session to re-unlock the bg selector
- [ ] thumbnail for rin

## Testing:
- Make sure Rin looks good
- Make sure CGs work again
- Make sure spritepack based outfit greetings work too
- Verify that if you're in another background prior to loading in on o31 (or get the o31 relaunch), loading in results in you back in spaceroom, with the bg selector locked

2020-10-25 20:19 UTC, ThePotatoGuy requested changes

2020-10-25 20:19 UTC, ThePotatoGuy commented on Monika After Story/game/script-holidays.rpy
> +        #5 - restart music
comment style only change, please revert

2020-10-25 23:16 UTC, ThePotatoGuy approved these changes

2020-10-26 00:00 UTC, ThePotatoGuy approved these changes

2020-10-26 01:00 UTC, ThePotatoGuy requested changes

2020-10-26 01:00 UTC, ThePotatoGuy commented on Monika After Story/game/sprite-chart.rpy
> +
This kind of prop is too broad. What characteristic of the braided hair makes it so marisa hat doesn't work with it? 

`no-hat` doesn't describe anything about the hairstyle itself, which makes it difficult for someone making a custom hairstyle to to determine if they need this prop or not.

2020-10-26 23:53 UTC, jmwall24 approved these changes

2020-10-27 00:04 UTC, ThePotatoGuy approved these changes

2020-10-27 01:05 UTC, Booplicate approved these changes

2020-10-27 01:11 UTC, Legendkiller21 approved these changes

2020-10-27 01:14 UTC, merged