I deleted our idle sprites
Monika-After-Story/MonikaModDev pull request #6634
Opened 2020-11-03 14:40 UTC by Booplicate

Implemented a new system for idle sprite management . Instead of ATL, this uses its own class `MASMoniIdleDisp`. 

Why?
- `ATL` is buggy. For example it likes to restart when we don't need, but refuses to restart when we do need it to. It also has issues with other transforms and transitions.
- `ATL` gives no control over it, the new disp allows to change exp with one method.
- With `ATL` we can't really get status of `ATL`, the disp allows us to get current exp, its duration, and much more.
- For `ATL` we kinda had to duplicate code, but now adding a new expression is a matter of writing one line.
- `ATL` would be a pain to use with the mood system. This disp is kinda a step towards mood.
- I think my disp is more optimized than `ATL` + `ConditionSwitch`.

The new disp completely mimics the old ATL regarding how it looks. Although, for ATL sprites "total weight" was always `1`, for the disp total weight depends on the weight of all exps. So this may need to be adjusted, since I used the old values for weights.

New:
- `MASMoniIdleDisp` - the new displayable to handle idle sprite.
- `MASMoniIdleExp` - a class to represent a single expression.
- `MASMoniIdleExpGroup` - a class to represent a group of exps. This is used when we need to show multiple exp one by one. It's a subclass of `MASMoniIdleExp`, so they share some props and methods (and basically can be treated the same).
- New return keys:
   - `idle_exp` - to force a single exp generated on the fly for a duration. For example: `return "idle_exp: 5eubsa, 5"`.
   - `idle_exp_group` - to force an exps (or a group of exps) by tag. If the tag doesn't exist, nothing will happen. If there's multiple exp with the same tag, we use weighted choice to select one. For example: `return "idle_exp_group: happy"`. NOTE: I haven't added any predefined groups yet.

NOTE: If we want to add more idle sprites for diff affection, then it's good time to do it.

### Testing:
- I had to change the wink transform, I haven't noticed any issues, but I'd ask to pay some attention to it.
- Please, verify that we have good idle sprites. Especially their parameters like weights/conditionals/exp codes.
- Verify loading times are fine, no freezes during switching from topic into idle, etc.
- Verify that `conditional`'d exps are only being shown if the condition is met, same for `aff_range`.
- Give the new system a try. Force a new exp, try to add or remove one during runtime.
- Play with the return keys, make sure we have everything we want for them.
- Verify no stranger things happen. Ideally this disp should fix all the issues with had with idle sprites.

2020-11-03 16:31 UTC, Booplicate commented
@ThePotatoGuy Idk why Travis doesn't pass, we may need some adjustments to it.

2020-11-03 18:15 UTC, ThePotatoGuy commented
did you have a replacement for 6atl_leftandright? that is also used in crash greeting.

regardless, you should alias the atl sprites for at least one version to prevent crashes.

2020-11-03 18:58 UTC, ThePotatoGuy requested changes
the build is failing because you defined `monika idle` image at init 500, but labels are parsed at init 0. the image needs to be defined earlier than 0.

also can you move the disp to sprite-chart in a new python early block?

2020-11-03 19:04 UTC, Booplicate commented
RenPy defined images at init 500, but sure thing.

2020-11-03 19:18 UTC, ThePotatoGuy commented
oh thats actually probably because the spritechecker doesnt consider an indented sprite normal. just define the image on the base indent.

2020-11-03 19:19 UTC, Booplicate commented
I'm dumb, we can't define the image early, it needs aff functions. We *have* to define it later.

2020-11-08 01:37 UTC, ThePotatoGuy requested changes

2020-11-08 14:44 UTC, Booplicate commented on Monika After Story/game/sprite-chart.rpy
> +            self.__validate_children_aff_range()
Eh, not sure why I even did this.

2020-11-11 00:31 UTC, multimokia requested changes

2020-11-11 00:31 UTC, multimokia commented on Monika After Story/game/event-handler.rpy
> +    RET_KEY_PATTERN_IDLE_EXP = re.compile(r"(?:(?<=\|)|(?<=^))\s*idle_exp\s*:\s*(?:(?P<exp>\d[a-z]{3,13})\s*,\s*(?P<duration>\d)|(?P<tag>\w+))\s*(?:(?=\|)|(?=$))")
While it's unlikely we'll need to use something over 10 seconds. We should still account for it.
```suggestion
    RET_KEY_PATTERN_IDLE_EXP = re.compile(r"(?:(?<=\|)|(?<=^))\s*idle_exp\s*:\s*(?:(?P<exp>\d[a-z]{3,13})\s*,\s*(?P<duration>\d+)|(?P<tag>\w+))\s*(?:(?=\|)|(?=$))")
```

2020-11-15 23:58 UTC, ThePotatoGuy submitted a review, later dismissed

2020-12-23 23:50 UTC, multimokia approved these changes

2021-01-03 02:58 UTC, ThePotatoGuy approved these changes

2021-01-03 02:58 UTC, merged