Update zz_selector.rpy
Monika-After-Story/MonikaModDev pull request #6682
Opened 2020-11-12 03:12 UTC by 20RaVen23

Updated zz_selector.rpy for earrings sprites in #6681

2020-11-12 03:13 UTC, Rai99 commented
Is that a

2020-11-12 03:16 UTC, 20RaVen23 commented
...That's bad, right?

2020-11-12 03:18 UTC, Rai99 commented
You generally aim for `content`.
[The guide to rebranching can be found here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-put-my-pull-request-in-the-wrong-branch-and-dont-want-to-suffer-the-wrath-of-devs-how-do-i-fix-it)

2020-11-12 03:25 UTC, 20RaVen23 commented
Sorry about that...

2020-11-13 20:01 UTC, multimokia commented
Going to close and reopen to jumpstart Travis

2020-11-13 20:05 UTC, multimokia requested changes

2020-11-13 20:05 UTC, multimokia commented on Monika After Story/game/zz_selector.rpy
> +        restartBlacklist=True
```suggestion
        restartBlacklist=True,
```

2020-11-13 20:19 UTC, multimokia requested changes

2020-11-13 20:19 UTC, multimokia commented on Monika After Story/game/zz_selector.rpy
> +label monika_earring_select:
```suggestion
label monika_earrings_select:
```

2020-11-13 23:28 UTC, ThePotatoGuy requested changes

2020-11-13 23:28 UTC, ThePotatoGuy commented on Monika After Story/game/zz_selector.rpy
> +        "wear": "Can you wear earrings?",
```suggestion
        "earrings": {
            "_ev": "monika_earrings_select",
            "_min-items": 1,
            "change": "Can you change your earrings?",
            "wear": "Can you wear earrings?",
        },
```

can you also move this up so its in alphabetical order with the rest of the ACS?

2020-11-15 23:55 UTC, ThePotatoGuy requested changes

2020-11-15 23:55 UTC, ThePotatoGuy commented on Monika After Story/game/zz_selector.rpy
> +        "earrings": {
move this block up between `clothes` and `hair` so it is in alphabetical order.

2020-11-20 16:27 UTC, ThePotatoGuy approved these changes

2020-11-20 16:28 UTC, multimokia approved these changes

2020-11-20 16:29 UTC, merged