[Tweaks] - 3rd anniversary, gender neutral line adjustment
Monika-After-Story/MonikaModDev pull request #6707
Opened 2020-11-20 06:08 UTC by lunulae

Just a tiny change to make this line relevant for other player genders.
If we like the original line, I could also do a version of this that checks for if the player is male instead.

2020-12-05 02:06 UTC, lunulae commented
Made some additional changes to the way this topic begins.

2020-12-21 17:10 UTC, multimokia requested changes
smol thing

2020-12-21 17:10 UTC, multimokia commented on Monika After Story/game/script-anniversary.rpy
> +    m 2hubsb "Wow... the time really has flown by, hasn't it?"
```suggestion
    m 2hubsb "Wow...{w=0.3}time really has flown by, hasn't it?"
```

2020-12-23 01:57 UTC, jmwall24 approved these changes

2020-12-23 01:58 UTC, multimokia approved these changes

2020-12-23 02:00 UTC, merged