Add pause between topics
Monika-After-Story/MonikaModDev pull request #6715
Opened 2020-11-21 19:59 UTC by Booplicate

Most of the time we want pushed/queued events to be triggered as soon as possible. But sometimes we need a more soft transition between topics (for example `monika_soft_rains`) so it doesn't look like she's changing her "mood" in seconds. First step was to give us control over idle exp in #6634. Next step is to add a little delay. While it won't be used by 70% of the topics, it will make the remaining 30% feel more natural.

### TODO:
- [x] allow trigger non-event labels anytime.
- [ ] add `skip_pause` to all the events that need it.

### Changes:
- new variable to control the delay between events `event_unpause_dt` (I put it n the `mas_globals` store).
- new return key to set pause 'til the next event `pause: x` where x is duration in seconds (`int`).
- new event rule `skip_pause` for events that should be triggered regardless of the current pause.
 - (fix) all greetings skip mid loop eval now.

### Testing:
- verify the return key is working properly
- verify Monika doesn't start another topic right after finishing another one if it set pause
- verify you can always start a convo with Monika regardless of pause.

2021-01-03 02:56 UTC, multimokia commented
Waiting on #6634

2021-01-03 17:46 UTC, multimokia commented
Removing `don't merge` as prerequisite has been merged.

2021-02-06 01:20 UTC, ThePotatoGuy requested changes

2021-02-06 01:20 UTC, ThePotatoGuy commented on Monika After Story/game/event-handler.rpy
> +                )
Seems to be all `or` conditions so simplify it.
```suggestion
                not is_paused
                or ev is None# This is to allow triggering non-event labels
                or "skip_pause" in ev.rules
```

2021-02-06 01:20 UTC, ThePotatoGuy commented on Monika After Story/game/event-handler.rpy
> +                        mas_globals.event_unpause_dt = datetime.datetime.now() + datetime.timedelta(seconds=int(_match.group("duration")))
UTC going forward
```suggestion
                        mas_globals.event_unpause_dt = datetime.datetime.utcnow() + datetime.timedelta(seconds=int(_match.group("duration")))
```

2021-02-06 19:49 UTC, ThePotatoGuy approved these changes

2021-02-20 02:06 UTC, ThePotatoGuy approved these changes

2021-02-20 08:15 UTC, Legendkiller21 approved these changes

2021-03-09 02:54 UTC, Legendkiller21 approved these changes

2021-03-19 04:29 UTC, ThePotatoGuy approved these changes

2021-03-19 04:31 UTC, merged