Diamond Earrings Spritepack
Monika-After-Story/MonikaModDev pull request #6729
Opened 2020-11-25 18:40 UTC by 20RaVen23

Kaiewe and I made some earrings. I asked him about what name should be fine as author and that was okay with him.

- Added reaction
- JSON
- Multimokia will add the needed sprites due some issues I was having, couldn't add them myself.

I already tested and everything seems fine.

2020-11-25 19:17 UTC, Booplicate requested changes
We use only lowercase characters in var and label names (because it's just more convenient). You'll need to rename the files as well.

2020-11-25 19:17 UTC, Booplicate commented on Monika After Story/game/zz_reactions.rpy
> +label mas_reaction_gift_acs_RaVen_earrings_diamond:
```suggestion
label mas_reaction_gift_acs_raven_earrings_diamond:
```

2020-11-25 19:17 UTC, Booplicate commented on spritepacks/released/RaVen & Kai/RaVen_earrings_diamond/mod_assets/monika/j/RaVen_acs_earrings_diamond.json
> +    "img_sit": "RaVen_earrings_diamond",
```suggestion
    "name": "raven_earrings_diamond",
    "img_sit": "raven_earrings_diamond",
```

2020-11-25 19:17 UTC, Booplicate commented on spritepacks/released/RaVen & Kai/RaVen_earrings_diamond/mod_assets/monika/j/RaVen_acs_earrings_diamond.json
> +        "thumb": "RaVen_earrings_diamond",
```suggestion
        "thumb": "raven_earrings_diamond",
```

2020-11-25 19:17 UTC, Booplicate commented on Monika After Story/game/zz_reactions.rpy
> +            (store.mas_sprites.SP_ACS, "RaVen_earrings_diamond")
```suggestion
            (store.mas_sprites.SP_ACS, "raven_earrings_diamond")
```

2020-11-30 00:52 UTC, TriniTDM commented
Those look beautiful...

2020-12-05 17:59 UTC, jmwall24 commented
Ok this sprite pack doesn't currently work with our hair. Any hairstyle with the right strand that goes in front of her body has the earring go behind that strand, even though that strand starts behind her ear. Will need a fix for this before this spritepack can love forward.

2021-05-04 00:02 UTC, multimokia commented
Waiting on #7148

2021-05-04 00:39 UTC, 20RaVen23 commented
![mytimehascome](https://user-images.githubusercontent.com/55263957/116949262-b391c200-ac4f-11eb-858b-809b7d542520.gif)

2021-09-01 03:04 UTC, closed without merging