Fix MacOS WRS issue
Monika-After-Story/MonikaModDev pull request #6773
Opened 2020-12-10 22:03 UTC by multimokia

As of #6265, a catch was introduced where Mac users, because we cannot check active window, fell through the function and wound up returning `None`, as such caused issues down the pipeline. This remedies that and optimizes other parts of zz_windowreacts.rpy

# Testing:
- [ ] Verify that windowreacts still work properly
- [ ] Verify no other issues

2020-12-10 22:20 UTC, ThePotatoGuy requested changes

2020-12-10 22:20 UTC, ThePotatoGuy commented on Monika After Story/game/zz_windowreacts.rpy
> +        except ImportError:
```suggestion
        except:
```
let's make this a blanket except so we don't crash at all

2020-12-10 22:20 UTC, ThePotatoGuy commented on Monika After Story/game/zz_windowreacts.rpy
> +        )
this looks more confusing than what it was previously. the lines here are just too long for `x if condition else y`

2020-12-10 22:20 UTC, ThePotatoGuy commented on Monika After Story/game/zz_windowreacts.rpy
> +                    active_winid = active_winid_prop.value[0]
```suggestion
                active_winid = active_winid_prop.value[0]
```

can drop the else since the if branch causes an early quit

2020-12-10 22:57 UTC, Booplicate approved these changes

2020-12-10 22:59 UTC, Legendkiller21 approved these changes

2020-12-10 23:01 UTC, jmwall24 approved these changes

2020-12-11 01:43 UTC, ThePotatoGuy approved these changes

2020-12-11 01:43 UTC, merged