Fix singleton
Monika-After-Story/MonikaModDev pull request #6854
Opened 2020-12-30 18:31 UTC by Booplicate

This saves us time explaining to people why they can't boot up the game and how to fix it.

### Changes:
- The exception now shows proper information to the user.
- We're catching `OSError 17` for windows now (because this is the actual "file already exists" error).
- Removed (commented out) logging; `singleton` logs to the same file in which renpy does, which leads to a big unreadable mess.
- Cleanup to make its code a bit more readable (no actual changes to how it works).

### Testing:
- verify we show the appropriate message on singleton crashes.

2020-12-30 19:30 UTC, multimokia requested changes
smol

2020-12-30 19:30 UTC, multimokia commented on Monika After Story/game/python-packages/singleton.py
> +                    "Another instance is already running, quitting. If the issue persist, restart your computer or manually delete '{0}'".format(
```suggestion
                    "Another instance is already running, quitting. If the issue persists, restart your computer or manually delete '{0}'".format(
```

2020-12-30 19:30 UTC, multimokia commented on Monika After Story/game/python-packages/singleton.py
> +                        "Another instance is already running, quitting. If the issue persist, restart your computer or manually delete '{0}'".format(
```suggestion
                        "Another instance is already running, quitting. If the issue persists, restart your computer or manually delete '{0}'".format(
```

2021-01-03 18:24 UTC, multimokia approved these changes

2021-01-11 23:18 UTC, ThePotatoGuy approved these changes

2021-01-11 23:18 UTC, merged