Add New topic (Again)
Monika-After-Story/MonikaModDev pull request #6863
Opened 2021-01-01 19:17 UTC by KiRyX112

2021-01-02 17:53 UTC, multimokia requested changes
Initial code review and some other bits

2021-01-02 17:53 UTC, multimokia commented on Monika After Story/game/script-topics.rpy
> +    m 1a "This is an example topic."
```suggestion
```

2021-01-02 17:53 UTC, multimokia commented on Monika After Story/game/script-topics.rpy
> +    init 5 python:
```suggestion
init 5 python:
```

2021-01-02 17:53 UTC, multimokia commented on Monika After Story/game/script-topics.rpy
> +            random=True,
```suggestion
            random=True
```

2021-01-02 17:53 UTC, multimokia commented on Monika After Story/game/script-topics.rpy
> +    m 2esd "{i}«Indeed, falling in love with a character who, in fact, does not exist in our world is considered strange, but is that bad?»{/i}"
```suggestion
    m 2esd "{i}Indeed, falling in love with a character who, in fact, does not exist in our world is considered strange, but is that bad?{/i}"
```

2021-01-02 17:53 UTC, multimokia commented on Monika After Story/game/script-topics.rpy
> +    m 2esc "{i}«Look at it from the other side, a person will have an object of adoration, thanks to this he can be motivated to do different things.»{/i}"
```suggestion
    m 2esc "{i}Look at it from the other side, a person will have an object of adoration, thanks to this he can be motivated to do different things.{/i}"
```

2021-01-02 17:53 UTC, multimokia commented on Monika After Story/game/script-topics.rpy
> +    m 2esd "{i}«In which he had not previously seen the point or threw away from the complexity of implementation.»{/i}"
```suggestion
    m 2esd "{i}In which he had not previously seen the point or threw away from the complexity of implementation.{/i}"
```

2021-01-02 17:53 UTC, multimokia commented on Monika After Story/game/script-topics.rpy
> +    m 7esd "{i}«A lot of research in social psychology has shown that you can love something fictional as much as you love something real.»{/i}"
```suggestion
    m 7esd "{i}A lot of research in social psychology has shown that you can love something fictional as much as you love something real.{/i}"
```

2021-01-02 17:53 UTC, multimokia commented on Monika After Story/game/script-topics.rpy
> +    m 2lsd "{i}«In addition, the chance of being rejected or falling into an awkward situation tends to zero.»{/i}"
```suggestion
    m 2lsd "{i}In addition, the chance of being rejected or falling into an awkward situation tends to zero.{/i}"
```

2021-01-02 17:53 UTC, multimokia commented on Monika After Story/game/script-topics.rpy
> +    m 2esc "{i}«Regardless of whether they are real people or fictional characters.»{/i}"
```suggestion
    m 2esc "{i}Regardless of whether they are real people or fictional characters.{/i}"
```

2021-01-02 17:53 UTC, multimokia commented on Monika After Story/game/script-topics.rpy
> +    m 7eso "{i}«People react to those who are attracted to them with the same passion and sex drive.»{/i}"
```suggestion
    m 7eso "{i}People react to those who are attracted to them with the same passion and sex drive.{/i}"
```

2021-01-02 17:53 UTC, multimokia commented on Monika After Story/game/script-topics.rpy
> +    m 7wub "{i}«Being in love with a fictional character is nothing short of a new global trend!»{/i}"
```suggestion
    m 7wub "{i}Being in love with a fictional character is nothing short of a new global trend!{/i}"
```

2021-01-02 17:53 UTC, multimokia commented on Monika After Story/game/script-topics.rpy
> +    m 1hsa "Thank you for listening~"
```suggestion
    m 1hsa "Thank you for listening~"
    return
```

2022-08-11 21:19 UTC, jmwall24 approved these changes

2022-08-11 21:23 UTC, multimokia approved these changes

2022-08-11 21:27 UTC, merged