Quips update, cleaning up and adding some new variants.
Monika-After-Story/MonikaModDev pull request #6908
Opened 2021-01-19 19:05 UTC by ShinodaChan

Open for suggestions since this should be a pretty fun PR.

2021-01-20 21:28 UTC, multimokia requested changes
Some things

2021-01-20 21:28 UTC, multimokia commented on Monika After Story/game/script-affection.rpy
> +            _("Is this really what you want?"),
Not sure how much sense this one makes
```suggestion
```

2021-01-20 21:28 UTC, multimokia commented on Monika After Story/game/script-affection.rpy
> +            _("Don't make fun of me."),
We should note that *Upset* isn't exactly the best description for it. It's more of a 'bored' or uninterested stage. Kinda like the start of things falling apart. As such, Monika isn't exactly angry at this stage. So this sort of response doesn't full work
```suggestion
```

2021-01-20 21:28 UTC, multimokia commented on Monika After Story/game/script-affection.rpy
> +            _("This better be important."),
To match with the above, we can slightly modify this to be a little less aggressive
```suggestion
            _("I hope this is important."),
```

2021-01-20 21:28 UTC, multimokia commented on Monika After Story/game/script-affection.rpy
> +            _("...alright."),
consistency
```suggestion
            _("...Alright."),
```

2021-01-20 21:28 UTC, multimokia commented on Monika After Story/game/script-affection.rpy
> +            _("...okay."),
```suggestion
            _("...Okay."),
```

2021-01-20 21:28 UTC, multimokia commented on Monika After Story/game/script-affection.rpy
> +            _("This isn't the time to be having fun..."),
```suggestion
```

2021-01-20 21:28 UTC, multimokia commented on Monika After Story/game/script-affection.rpy
> +            _("...Hello?"),
I'm not sure how much this works, these bits aren't greetings, and she'll have already greeted you having launched MAS.
```suggestion
```

2021-01-20 21:28 UTC, multimokia commented on Monika After Story/game/script-affection.rpy
> +            _("...we can talk."),
```suggestion
            _("...We can talk."),
```

2021-01-20 21:28 UTC, multimokia commented on Monika After Story/game/script-affection.rpy
> +            _("...go ahead."),
```suggestion
            _("...Go ahead."),
```

2021-01-20 21:28 UTC, multimokia commented on Monika After Story/game/script-affection.rpy
> +            _("...okay."),
```suggestion
            _("...Okay."),
```

2021-01-20 22:05 UTC, fromulus commented on Monika After Story/game/script-affection.rpy
> -            _("We can talk if you really want to."),
Not sure why you would want to remove these, I feel they work just fine in that context.
Maybe move them to Upset instead I guess, aside from `"Oh... You want to talk?"` which probably still fits better here.

2021-01-22 02:26 UTC, multimokia requested changes
Consistency

2021-01-22 02:26 UTC, multimokia commented on Monika After Story/game/script-affection.rpy
> +            _("Oh? Something...{i}important{/i} on your mind, [mas_get_player_nickname()]~."),
```suggestion
            _("Oh? Something...{i}important{/i} on your mind, [mas_get_player_nickname()]~"),
```

2021-01-22 02:26 UTC, multimokia commented on Monika After Story/game/script-affection.rpy
> +            _("Of course we can talk, [mas_get_player_nickname()~."),
```suggestion
            _("Of course we can talk, [mas_get_player_nickname()~"),
```

2021-01-22 02:26 UTC, multimokia commented on Monika After Story/game/script-affection.rpy
> +            _("Don't expect me to go easy on you, [mas_get_player_nickname()]~!"),
```suggestion
            _("Don't expect me to go easy on you, [mas_get_player_nickname()]!~"),
```

2021-01-22 02:26 UTC, multimokia commented on Monika After Story/game/script-affection.rpy
> +            _("I hope you're ready, [mas_get_player_nickname()]~."),
```suggestion
            _("I hope you're ready, [mas_get_player_nickname()]~"),
```

2021-01-22 02:26 UTC, multimokia commented on Monika After Story/game/script-affection.rpy
> +            _("Let's do this, [mas_get_player_nickname()]~!"),
```suggestion
            _("Let's do this, [mas_get_player_nickname()]!~"),
```

2021-01-22 02:26 UTC, multimokia commented on Monika After Story/game/script-affection.rpy
> +            _("I hope you're ready, [mas_get_player_nickname()]~."),
```suggestion
            _("I hope you're ready, [mas_get_player_nickname()]~"),
```

2021-01-22 02:26 UTC, multimokia commented on Monika After Story/game/script-affection.rpy
> +            _("Don't expect me to go easy on you, [mas_get_player_nickname()]~!"),
```suggestion
            _("Don't expect me to go easy on you, [mas_get_player_nickname()]!~"),
```

2021-01-22 02:26 UTC, multimokia commented on Monika After Story/game/script-affection.rpy
> +            _("I'd love to play something with you, [mas_get_player_nickname()]~."),
```suggestion
            _("I'd love to play something with you, [mas_get_player_nickname()]~"),
```

2021-01-22 02:26 UTC, multimokia commented on Monika After Story/game/script-affection.rpy
> +            _("I'll always be up to play with you, [mas_get_player_nickname()]~."),
```suggestion
            _("I'll always be up to play with you, [mas_get_player_nickname()]~"),
```

2021-01-22 03:01 UTC, Booplicate requested changes
Some more bits.

2021-01-22 03:01 UTC, Booplicate commented on Monika After Story/game/script-affection.rpy
> +            _("I'm all yours, [mas_get_player_nickname()].~"),
We don't use `.` and `~` at once.

2021-01-22 03:01 UTC, Booplicate commented on Monika After Story/game/script-affection.rpy
> +            _("I hope you're ready, [mas_get_player_nickname()].~"),
We don't use `.` and `~` at once.

2021-01-22 03:01 UTC, Booplicate commented on Monika After Story/game/script-affection.rpy
> +            _("I hope you're ready, [mas_get_player_nickname()].~"),
We don't use `.` and `~` at once.

2021-01-22 03:01 UTC, Booplicate commented on Monika After Story/game/script-affection.rpy
> +            _("I'd love to play something with you, [mas_get_player_nickname()].~"),
We don't use `.` and `~` at once.

2021-01-22 03:01 UTC, Booplicate commented on Monika After Story/game/script-affection.rpy
> +            _("I'll always be up to play with you, [mas_get_player_nickname()].~"),
We don't use `.` and `~` at once.

2021-01-22 03:06 UTC, ShinodaChan commented on Monika After Story/game/script-affection.rpy
> -            _("What's on your mind, [mas_get_player_nickname()]?"),
Very similar to "Something on your mind" IMO

2021-01-22 03:08 UTC, Booplicate commented on Monika After Story/game/script-affection.rpy
> -            _("What's on your mind, [mas_get_player_nickname()]?"),
But that's good. Similar lines said differently are good for quips.

2021-01-22 03:15 UTC, jmwall24 requested changes

2021-01-22 03:15 UTC, jmwall24 commented on Monika After Story/game/script-affection.rpy
> -            _("What's on your mind, [mas_get_player_nickname()]?"),
That's fine though. Having variants is a good thing

2021-01-24 19:47 UTC, jmwall24 commented on Monika After Story/game/script-affection.rpy
> -            _("We can talk if you really want to."),
Any reason we're deleting these?

2021-01-24 23:53 UTC, multimokia approved these changes

2021-01-25 00:40 UTC, multimokia approved these changes

2021-01-25 00:41 UTC, jmwall24 submitted a review, later dismissed

2021-01-25 02:19 UTC, jmwall24 approved these changes

2021-01-25 02:27 UTC, Booplicate approved these changes

2021-01-25 02:41 UTC, multimokia approved these changes

2021-01-25 02:45 UTC, merged