Removed Sensitive Mode
Monika-After-Story/MonikaModDev pull request #6923
Opened 2021-01-24 22:56 UTC by ThePotatoGuy

TODO:
- [ ] need to review if there are locations that use sensitive mode that should be changed to a different flag
- [ ] need to decide if should be replaced with a horror setting instead

# Key Changes
* Removes sensitive mode setting

2021-07-03 18:51 UTC, Legendkiller21 requested changes
Some small stuff

2021-07-03 18:51 UTC, Legendkiller21 commented on Monika After Story/game/script-topics.rpy
> +            not renpy.seen_label("monika_sayori")
```suggestion
            not mas_getEVL_shown_count("monika_sayori")
```
The label is marked as seen the moment we get in so we should check the `shown_count` in this one

2021-07-03 18:51 UTC, Legendkiller21 commented on Monika After Story/game/script-topics.rpy
> +    if mas_safeToRefDokis():
```suggestion
    if not mas_safeToRefDokis():
```

2021-07-05 17:02 UTC, Legendkiller21 approved these changes

2021-07-13 01:46 UTC, multimokia approved these changes

2021-07-19 22:14 UTC, ThePotatoGuy commented
@jmwall24 can you finish your review on this before the end of the week? I want to unstable this soon.

2021-07-19 22:29 UTC, jmwall24 commented
Sorry, I reviewed this last week, forgot to actually submit the review.

2021-07-19 22:29 UTC, jmwall24 approved these changes

2021-07-19 22:30 UTC, multimokia commented
au revoir, sensitive.

2021-07-19 22:30 UTC, merged