Windowreacts but they're implemented how they should've been from the start
Monika-After-Story/MonikaModDev pull request #7006
Opened 2021-02-17 04:12 UTC by multimokia

Windowreacts now use regexp's to check the active window handle content

## Changes:
- `mas_getActiveWindow` has been renamed to `mas_getActiveWindowHandle` to be more specific to what it does
- `_getActiveWindow_Linux` renamed -> `_mas_getActiveWindowHandle_Linux`
- `_getActiveWindow_Windows` renamed -> `_mas_getActiveWindowHandle_Window`
- The `inclusive` rule for checking active window keys has been removed as this can be entirely handled by regex much better
- Windowreacts no longer uses `.lower()`, (#6802). Instead, it uses `re.IGNORECASE`.
- `mas_wrs_r34m` actually checks affection for the exp response. It also makes use of the new idle disp. Additionally, it works for more than just one site now.
- WRS Dev topics have been updated accordingly.

## Testing:
- Verify all windowreacts still work
- Verify r34 reaction has appropriate reactions for aff levels (just two levels, below enam, and enam+)
- Verify no crashes
- Verify other language chars work properly now (again ref to #6802)

2021-03-09 12:45 UTC, Booplicate requested changes

2021-03-09 12:45 UTC, Booplicate commented on Monika After Story/game/script-windowreacts.rpy
> +        if choice == 1:
```suggestion
        if choice == 1 and mas_isMoniNormal(higher=True):
```

2021-03-09 12:45 UTC, Booplicate commented on Monika After Story/game/script-windowreacts.rpy
> +        elif choice == 2:
```suggestion
        elif choice == 2 and mas_isMoniAff(higher=True):
```

2021-03-09 15:43 UTC, Booplicate submitted a review, later dismissed

2021-03-13 18:54 UTC, Booplicate submitted a review, later dismissed

2021-03-16 15:09 UTC, Booplicate commented on Monika After Story/game/script-windowreacts.rpy
> +            category=[r"(?i)(((r34|rule\s?34).*monika)|(post \d+:[\w ]+monika)|(.*monika.*(r34|rule34)))"],
~~We put way too much time into this~~
```suggestion
            category=[r"(?i)(((r34|rule\s?34).*monika)|(post \d+:[\w\s]+monika)|(monika.*(r34|rule\s?34)))"],
```

2021-03-18 10:02 UTC, Legendkiller21 approved these changes

2021-03-18 18:10 UTC, jmwall24 approved these changes

2021-03-18 21:51 UTC, Booplicate approved these changes

2021-03-18 21:55 UTC, merged