Fix F29 pbday mhs correction
Monika-After-Story/MonikaModDev pull request #7092
Opened 2021-03-10 17:14 UTC by multimokia

Fix #7091 

# Testing
- Make sure all unit tests pass
- Make sure entering F29 as player bday doesn't crash when trying to adjust the mhs for it.
- Verify dates on the mhs are correct still (for f29, since it's currently Mar 10 at the time of writing, both should be incrementing the year by 1 (so 2022)
- Verify cases for other trigger dates still get set properly (these are also covered by unit tests, they can be referred to to see the values needed)

2021-03-19 04:26 UTC, ThePotatoGuy submitted a review, later dismissed

2021-04-28 00:07 UTC, multimokia commented
Adding don't merge on this. Needs fixes to calendar. Will make them in a separate PR as a major portion of the data structure may need to change for this to work properly.

2021-04-28 01:30 UTC, ThePotatoGuy commented on Monika After Story/game/zz_calendar.rpy
> +                if self.selected_month == 3 and self.selected_year % 4 != 0:
mm unfortunate that this isn't true if the year is divisible by 100 unless its divisible by 400.

2021-04-28 18:03 UTC, ThePotatoGuy requested changes

2021-04-28 18:03 UTC, ThePotatoGuy commented on Monika After Story/game/zz_calendar.rpy
> +    def mas_isLeapYear(year):
actually the better way to do this is just try to build the Feb 29 date object and catch the exception. (See `add_years` in `definitions`)

2021-05-03 14:03 UTC, Booplicate approved these changes

2021-05-04 04:14 UTC, ThePotatoGuy approved these changes

2021-05-04 04:27 UTC, merged