Jsonified Sprite Maps
Monika-After-Story/MonikaModDev pull request #7102
Opened 2021-03-14 22:08 UTC by multimokia

Since #6864, we've had smugleft and right but not had them added to the sprite checker's map, causing Travis issues (#7101)

This PR addresses it by jsonifying the sprite maps and reading from the json within MAS and within the `StaticSprite` class in the spritechecker utility.

This way, we can add sprites by simply adding them to the map, and both MAS and the utils get updated together.

## Testing:
- Verify in-MAS sprites still work correctly with this system
- Verify spritechecker works with the new system and smug left/right works properly.

2021-03-15 21:13 UTC, ThePotatoGuy requested changes

2021-03-15 21:13 UTC, ThePotatoGuy commented on Monika After Story/game/sprite-decoder.rpy
> +            store.mas_utils.writelog("[ERROR]: Failed to load sprite_map json.")
if this happens, we don't have a fallback right? We should just raise an exception.

2021-03-16 01:25 UTC, Booplicate requested changes

2021-03-16 01:25 UTC, Booplicate commented on Monika After Story/game/sprite-decoder.rpy
> +        with open(store.os.path.join(renpy.config.gamedir, "mod_assets", "sprite_map.json"), "r") as jsonfile:
I think `with` doesn't handle exceptions. So if the file is empty/corrupted or doesn't exist at all, we'd just crash here, never reaching the `None` check below. If you want to use that custom exception, you'd probably have to use `try/except` here.

2021-03-16 01:25 UTC, Booplicate commented on Monika After Story/game/sprite-decoder.rpy
> +        EYEBROW_MAP = jobj["eyebrows"]
And maybe these should be in a `try/except` block too, since direct access of fields?

2021-03-16 01:25 UTC, Booplicate commented on tools/sprite.py
> +    def _loadSpriteMapData():
Same applies to this function since they are identical.

2021-03-19 04:18 UTC, ThePotatoGuy approved these changes

2021-03-19 05:46 UTC, Legendkiller21 approved these changes

2021-03-20 10:00 UTC, Booplicate approved these changes

2021-03-21 01:25 UTC, merged