Very Early mas_log
Monika-After-Story/MonikaModDev pull request #7192
Opened 2021-04-28 21:20 UTC by multimokia

`renpy.log` (or `renpy.exports.log`) is extremely unreliable between init `-999` and `-995`. Sometimes it exists as one thing, sometimes it's not that, additionally because there is no logfile created internally at the time, we simply cannot trust this to log for us at these levels.

As such, I have moved the logging portions of `mas_utils` into `python early`, and it should be the first init block we have to run for MAS.

# Affected Members:
- `MASMacLog`
- `macLogOpen`
- `logcreate`
- `writelog`
- `wtf`
- `writestack`
- `logrotate`
- `tryparseint`
- `mas_mac_log_cache`
- `mas_log`
- `mas_log_open`

# Testing:
- Verify no crashes
- Verify logging still works
- Verify all functions exists as normal
- Verify logs still get rotated
- Verify logs work properly during early init levels (`-999` - `-995`)

2021-04-28 22:07 UTC, ThePotatoGuy requested changes
can the file be named `00utils`? Decent chance that we'll be adding more than just logging to here in the future.

2021-05-22 22:19 UTC, ThePotatoGuy submitted a review, later dismissed

2021-05-23 09:30 UTC, Booplicate requested changes

2021-05-23 09:30 UTC, Booplicate commented on Monika After Story/game/00utils.rpy
> +                        self.file = codecs.open(fn, mode, "utf-8")
Should import `codecs`.

2021-05-23 09:30 UTC, Booplicate commented on Monika After Story/game/00utils.rpy
> +                    self.write("%s", platform.platform())
Should import `platform`.

2021-05-23 09:30 UTC, Booplicate commented on Monika After Story/game/00utils.rpy
> +        writelog("".join(traceback.format_stack()))
Should import `traceback`.

2021-05-23 09:30 UTC, Booplicate commented on Monika After Story/game/00utils.rpy
> +        copyfile(old_path, new_path)
`copyfile` is undefined.

2021-05-23 09:30 UTC, Booplicate commented on Monika After Story/game/00utils.rpy
> +        trydel(new_path)
`trydel` is undefined.

2021-05-24 02:37 UTC, ThePotatoGuy approved these changes

2021-05-28 03:58 UTC, ThePotatoGuy approved these changes

2021-05-28 11:19 UTC, Booplicate approved these changes
Can't test mac logs, but the code looks fine now.

2021-05-29 09:18 UTC, Legendkiller21 approved these changes

2021-06-01 06:47 UTC, merged