Adding three new songs.
Monika-After-Story/MonikaModDev pull request #7235
Opened 2021-05-22 18:15 UTC by Retrolovania

Added three new songs for Monika to sing, them being:

-Fly Me to the Moon (Frank Sinatra)
-On the Front Porch (Burl Ives)
-Heaven (Bryan Adams)

2021-05-22 21:05 UTC, jmwall24 requested changes
Bit of an issue here with formatting for the first and third songs. You made these 'long' songs but we require all songs (that aren't special events) to have short versions and then it's an option for those to unlock the long (full) versions. Short songs have the short commentary after them like you have here, but the long versions should just full the full lyrics with no commentary. You need to pick shorter segments of the songs for the short versions and then use your bit of commentary that you have here at the end of those. Then if you want, you can add long versions which should just be the full lyrics. The second song is fine. Also, `return` is indented incorrectly for all 3 songs, it needs to be one indent in from `label` not in line with it.

2021-05-22 21:12 UTC, Retrolovania commented
I see. Very well. I'll get on 'em as soon as I can.

2021-07-06 19:32 UTC, Retrolovania commented
Any more edits needed, per chance?
Might add a fourth song at some point soon.

2021-07-26 01:34 UTC, multimokia submitted a review, later dismissed

2021-07-26 02:00 UTC, jmwall24 approved these changes

2021-07-26 03:09 UTC, multimokia approved these changes

2021-07-26 03:09 UTC, merged