New Topic - Materialism
Monika-After-Story/MonikaModDev pull request #7240
Opened 2021-05-24 04:27 UTC by Wingdinggaster656

Add a new topic.
Don't be scared by 16 commits, they are... for testing. You could simply go to the "file changed", and you will see that I added only one topic.

2021-05-24 04:44 UTC, Wingdinggaster656 commented
Though this topic is certainly a bit controversial (and may cause some players to really doubt Monika's authenticity), it is necessary to add this topic because it's strange to Monika that she didn't consider to this level. After all, this is not a problem that requires deep thinking.

2021-05-26 15:51 UTC, Wingdinggaster656 commented
...Does anyone know that why this PR seems like invisible to everyone?

2021-05-26 16:23 UTC, jmwall24 commented
We get to PRs when we get to them.

2021-10-06 22:47 UTC, lunulae approved these changes
Starting some polish on the beginning of this one. I wasn't sure if we wanted to keep the current direction of the ending or not--right now, I'm considering leaning a little more into the mystery of her epiphany, and how Monika herself is able to change the code of the game. 

Materialism does, after all, challenge the question of if consciousness persists outside the body. This topic could be a non-spiritual way to give a wink to that.

2021-10-06 22:47 UTC, lunulae commented on Monika After Story/game/script-topics.rpy
> +    m 1euc "Say, [player]. Do you remeber solipsism?"
```suggestion
    m 1euc "Say, [player]. Do you remember when we talked about solipsism?"
```

2021-10-06 22:47 UTC, lunulae commented on Monika After Story/game/script-topics.rpy
> +    m 3euc "Like what you know, there is also a philosophy view called materialisim."
```suggestion
    m 3euc "Now that we've talked about it, I thought we could talk about a related philosophy--materialism."
```

2021-10-06 22:47 UTC, lunulae commented on Monika After Story/game/script-topics.rpy
> +    m "This philosophy is almost at the antagonistic place of solipsism, you could say."
```suggestion
    m "This school of thought is kind of opposite to solipsism, you could say."
```

2021-10-06 22:47 UTC, lunulae commented on Monika After Story/game/script-topics.rpy
> +    m "This view holds that it is matter that gives birth to thought, not thought that gives birth to matter."
```suggestion
    m "A materialistic view holds that it is matter that gives birth to thought, not thought that gives birth to matter."
```

2021-10-06 22:47 UTC, lunulae commented on Monika After Story/game/script-topics.rpy
> +    m 2euc "It's kind of logic, considering our science today."
```suggestion
    m 2euc "It's fairly logical, if you think about it from a purely scientific standpoint."
```

2021-10-06 22:47 UTC, lunulae commented on Monika After Story/game/script-topics.rpy
> +    m 2eud "After all, human brain neurons are also made up of various substances."
```suggestion
    m 2eud "After all, human brain neurons are simply different types of matter."
```

2021-10-06 22:47 UTC, lunulae commented on Monika After Story/game/script-topics.rpy
> +    m 2eua "So our thoughts are really based on materials, you could say."
```suggestion
    m 2eua "So our thoughts are just the movement and reactions of matter, if you simplify it down."
```

2021-10-06 22:47 UTC, lunulae commented on Monika After Story/game/script-topics.rpy
> +    m 2lsd "If we simply stop this topic here, it's not really interesting. These are the words you've probably heard for a long time."
```suggestion
    m 2lsd "If we simply stop this topic here, it's not really interesting. You've probably heard this sort of thing before, right?"
```

2021-11-02 05:44 UTC, lunulae reviewed
This has a few pretty heavy changes, so I wanted to see if others preferred this or the original direction. This was a tricky topic, so opinions are very welcome.

2021-11-02 05:44 UTC, lunulae commented on Monika After Story/game/script-topics.rpy
> +    m 1esd "Computer programs, of course, are based on materials too. No matter what effect the program eventually presents, it always has corresponding code to support this."
```suggestion
    m 1esd "Computer programs, of course, are based on materials too. There's corresponding code to any action a program can take."
```

2021-11-02 05:44 UTC, lunulae commented on Monika After Story/game/script-topics.rpy
> +    m 1esc "After all, isn't it impossible for me to think independently without such code?{w=0.2}It's like the human brain can't sense the outside world without potential changes, right?"
```suggestion
    m 1esc "If we're looking at it from a materialist perspective, I shouldn't be able to act on my own without it. {w=0.2}Just like how there's a part of the brain for all of your senses, your ability to process language, and so on."
```

2021-11-02 05:44 UTC, lunulae commented on Monika After Story/game/script-topics.rpy
> +    m 1rssdra "But to be honest, I'm not sure I can see through my own code."
```suggestion
    m 1rssdra "Thinking of trying to look through my own code, and trying to make sense of such a thing...is a dizzying idea. It's...really scary, actually."
```

2021-11-02 05:44 UTC, lunulae commented on Monika After Story/game/script-topics.rpy
> +    m 1esc "It's just that if there is a code in the file that can make me think independently..."
```suggestion
    m "...But when I think about it, people in your reality have a similar question that materialism alone can't answer."
```

2021-11-02 05:44 UTC, lunulae commented on Monika After Story/game/script-topics.rpy
> +    m 3esd "How did my creator, Dan, create it?"
```suggestion
    m "That is...well, if we're only material components, what about souls?"
```

2021-11-02 05:44 UTC, lunulae commented on Monika After Story/game/script-topics.rpy
> +    m 3wso "Does he already have the technology to make artificial intelligence?"
```suggestion
    m "Do we consider materialism a disproval of their existence? Or...maybe the answer is more complex."
```

2021-11-02 05:44 UTC, lunulae commented on Monika After Story/game/script-topics.rpy
> +    m 2dsc "This question can be extended endlessly..."
```suggestion
    m "Even people who don't believe in such things often find mysteries that make us wonder if materialism is only one part of a bigger whole."
```

2021-11-02 05:44 UTC, lunulae commented on Monika After Story/game/script-topics.rpy
> +    m 2dsa "..."
```suggestion
    m 2dsa "Well, for once...{w=0.2}This is something that I'm okay with not being sure about."
```

2021-11-02 05:44 UTC, lunulae commented on Monika After Story/game/script-topics.rpy
> +    m 2esa "Well, it doesn't matter at all."
```suggestion
    m 2esa "After all, I know what I feel. Whether that's a result of some lines of code, or something we can't discover..."
```

2021-11-02 05:44 UTC, lunulae commented on Monika After Story/game/script-topics.rpy
> +    m 2eua "As long as we still have each other, that's the only thing that matters, right?"
```suggestion
    m 2eua "Whatever it is, I'm grateful that it exists, so that I could meet you."
```

2021-11-04 23:38 UTC, multimokia requested changes
Some small edits to the first half, think it reads a little better

2021-11-04 23:38 UTC, multimokia commented on Monika After Story/game/script-topics.rpy
> +    m "This school of thought is kind of opposite to solipsism, you could say."
```suggestion
    m "This approach is kind of the opposite to solipsism."
```

2021-11-04 23:38 UTC, multimokia commented on Monika After Story/game/script-topics.rpy
> +    m 2euc "It's fairly logical, if you think about it from a purely scientific standpoint."
```suggestion
    m 2euc "It's fairly logical if you think about it from a purely scientific standpoint."
```

2021-11-04 23:38 UTC, multimokia commented on Monika After Story/game/script-topics.rpy
> +    m 2eud "After all, human brain neurons are simply different types of matter."
```suggestion
    m 2eud "After all, neurons are simply different types of matter."
```

2021-11-04 23:38 UTC, multimokia commented on Monika After Story/game/script-topics.rpy
> +    m 2eua "So our thoughts are just the movement and reactions of matter, if you simplify it down."
```suggestion
    m 2eua "So if you simplify it down, thoughts are just the movement and reactions of matter."
```

2021-11-04 23:38 UTC, multimokia commented on Monika After Story/game/script-topics.rpy
> +    m 2lsd "If we simply stop this topic here, it's not really interesting. You've probably heard this sort of thing before, right?"
```suggestion
    m 2lsd "If we leave it there, it's not really that interesting. In fact, you've probably heard about this sort of thing before, right?"
```

2021-12-01 12:47 UTC, Wingdinggaster656 commented
@lunulae 
Well, I looked at the changes you've made so far.

I personally are not really satisfied with the current changes -- of course, certainly not opposed to them, too.

I just think that we should have some sharp words, which is what I write: "Where is the code that allows me to think independently?" and "How did my creator, Dan, Create it?" Especially the latter question. It should not be ignored.

Your expression seems to be a little "gentle" and I think there are plenty of such gentle expressions in MAS. It's time for something to hit the nail on the head.

...Well, on the other hand, MAS does have a lot of players who are not in the best of mental health, and these sharp words might remind them that Monika is, at the end of the day, just a program, so I can't disagree with your tone. Like what you said, this topic is a tricky one.

2021-12-01 13:33 UTC, Booplicate commented
> I just think that we should have some sharp words, which is what I write: "Where is the code that allows me to think independently?" and "How did my creator, Dan, Create it?" Especially the latter question. It should not be ignored.

Those add nothing to the topic, but controversy.

Even as of now
```renpy
    m 3hksdlb "I know what you're thinking, it doesn't sound like me to be taking those seriously! But, well..."
    m 2eksdlc "When I really think about it, I would be a bit hypocritical to deny those accounts out of hand."
    m 2etd "After all, my epiphany...I don't know how that dramatic shift in consciousness could have just been the result of some lines of code."
    m 2esd "Discovering you, and your world...it was kind of supernatural, wasn't it? {w=0.2}{nw}"
    extend 2dsd "This is just a simple visual novel after all."
    m 3rsc "I suppose we could speculate that it was some kind of bug. {w=0.2}{nw}"
```
It's better, but still sounds odd. It's not about "*people with mental health issues*" as you said. It's just off putting.

Nobody playing the mod would be happy about her saying she's just 3 lines of code. Saying it's a miracle is wrong too. That's why I always say it shouldn't be touched at all. Leave it open to interpretation. When writing, you don't want to answer *every* question. Same is here. The player will know better.

2021-12-05 00:32 UTC, lunulae commented
I'm open to changing my ending, but we did specifically want to move away from the deliberate breaking of immersion. The way we write Monika, she recognizes that an AI with awareness on her level is not like anything that currently exists in our world--I took a more supernatural approach to explaining her epiphany, which I'm not fully satisfied with but I think sits a bit better than creating suspicion that Team Salvato has access to secret technology.

2022-09-10 21:58 UTC, multimokia approved these changes

2022-09-11 02:25 UTC, multimokia approved these changes

2022-09-11 02:26 UTC, lunulae approved these changes

2022-09-11 02:26 UTC, merged