New love poem greeting
Monika-After-Story/MonikaModDev pull request #7303
Opened 2021-06-07 05:28 UTC by Erenussocrates

Decided to contribute a new love poem greeting that I came up with myself. Hope it's fine.

2021-06-07 21:15 UTC, multimokia requested changes
Syntax issues. `init 5 python` should be non-indented, all text tags go within the quotes.

2021-06-07 21:15 UTC, multimokia commented on Monika After Story/game/script-greetings.rpy
> +    init 5 python:
```suggestion
init 5 python:
```

2021-06-07 21:15 UTC, multimokia commented on Monika After Story/game/script-greetings.rpy
> +    m 5dkc {i}"Everytime you go, my world darkens,\nGardens of lifeless depression."{/i}
```suggestion
    m 5dkc "{i}Everytime you go, my world darkens,\nGardens of lifeless depression.{/i}"
```

2021-06-07 21:15 UTC, multimokia commented on Monika After Story/game/script-greetings.rpy
> +    m 5ekbla {i}"When you are back, it feels like heaven,\nSecond to none, impossible to bargain."{/i}
```suggestion
    m 5ekbla "{i}When you are back, it feels like heaven,\nSecond to none, impossible to bargain.{/i}"
```

2021-06-07 21:15 UTC, multimokia commented on Monika After Story/game/script-greetings.rpy
> +    m 1skbfa {i}"I will give everything to feel this way,\nAwaiting the one I hold dearest."{/i}
```suggestion
    m 1skbfa "{i}I will give everything to feel this way,\nAwaiting the one I hold dearest.{/i}"
```

2021-06-07 21:15 UTC, multimokia commented on Monika After Story/game/script-greetings.rpy
> +    m 1hubfa {i}"Even if it's every single day,\nWithout a doubt, you are the nearest."{/i}
```suggestion
    m 1hubfa "{i}Even if it's every single day,\nWithout a doubt, you are the nearest.{/i}"
```

2021-06-07 21:15 UTC, multimokia commented on Monika After Story/game/script-greetings.rpy
> +    m 2tubsb {i}"Nearest to my heart..."{/i}
```suggestion
    m 2tubsb "{i}Nearest to my heart...{/i}"
```

2021-06-12 11:48 UTC, Erenussocrates commented
I've made the requested changes, anyone who can review?

2021-06-12 11:58 UTC, Booplicate commented
We'll review once we get time, don't worry we didn't forget.

2021-07-12 01:11 UTC, jmwall24 requested changes
Overall I like the poem, but the first line is a bit dark and fits more if she were still going to the void when the player leaves. As it is now, it comes off as a huge guilt trip, so could you come up with a different first line that isn't quite as dark?

2021-07-15 11:10 UTC, Erenussocrates commented
It didn't feel as dark to me considering the poems she wrote in the story, and even if it would feel like a guilt trip, I think that would be okay since she does come off as manipulative towards the player at times. 

But nevertheless, I give you full permission to change this to the way you like if you feel this isn't suitable, as long as you maintain the rhyme. I've paid special attention to make each line rhyme twice.

2021-09-20 05:33 UTC, lunulae reviewed
Trying a rework of the first line out, how does this sound?

2021-09-20 05:33 UTC, lunulae commented on Monika After Story/game/script-greetings.rpy
> +    m 5dkc "{i}Everytime you go, my world darkens,\nGardens of lifeless depression.{/i}"
```suggestion
    m 5dkc "{i}Alone I ask a solemn question,\nWhat could grow in an unlit garden?{/i}"
```

2021-09-20 05:33 UTC, lunulae commented on Monika After Story/game/script-greetings.rpy
> +    m 5ekbla "{i}When you are back, it feels like heaven,\nSecond to none, impossible to bargain.{/i}"
```suggestion
    m 5ekbla "{i}When you return, it feels like heaven,\nSecond to none, impossible to bargain.{/i}"
```

2022-02-05 07:34 UTC, lunulae commented on Monika After Story/game/script-greetings.rpy
> +    m 4hksdlb "Anyway, welcome back darling!"
```suggestion
    m 4hksdlb "Anyway, welcome back, [mas_get_player_nickname()]!"
```

2022-09-11 01:05 UTC, multimokia submitted a review, later dismissed

2022-09-11 01:40 UTC, lunulae approved these changes

2022-09-11 02:53 UTC, Booplicate requested changes

2022-09-11 02:53 UTC, Booplicate commented on Monika After Story/game/script-greetings.rpy
> +    jump monikaroom_greeting_choice
Weird jump, probably from merging?

2022-09-11 02:53 UTC, Booplicate commented on Monika After Story/game/script-greetings.rpy
> +    )
Can we add a rule for absence check?

2022-09-11 02:53 UTC, Booplicate commented on Monika After Story/game/script-greetings.rpy
> +label greeting_lovepoem1:
Maybe we could use a more specific name? `greeting_poem_shadows_in_garden`?

2022-09-11 18:56 UTC, jmwall24 approved these changes

2022-09-11 19:02 UTC, Booplicate approved these changes

2022-09-11 19:20 UTC, merged