[Drafts] - 6+7 Anniversaries
Monika-After-Story/MonikaModDev pull request #7324
Opened 2021-06-11 05:59 UTC by lunulae

We definitely don't need these for a long time (if at all) but I had a few ideas to toss out juuuust in case.

Feel free to rework or delete these if annis get reworked, I'm just throwin' stuff at a wall and seeing what sticks.

2021-07-03 17:14 UTC, multimokia requested changes
Some prelim things

2021-07-03 17:14 UTC, multimokia commented on Monika After Story/game/script-anniversary.rpy
> +    m 1hub "Speaking of sweet things...a common sixth anniversary theme is candy!"
```suggestion
    m 1hub "Speaking of sweet things...{w=0.3}a common sixth anniversary theme is candy!"
```

2021-07-03 17:14 UTC, multimokia commented on Monika After Story/game/script-anniversary.rpy
> +    m 1rkbla "But I still think it's a very sweet sentiment."
```suggestion
    m 1rkbla "But I still think it's a sweet sentiment."
```

2021-07-03 17:14 UTC, multimokia commented on Monika After Story/game/script-anniversary.rpy
> +    extend 3hua "you should get yourself a nice treat to eat for the occasion!"
~~Give Monika your CC info wen~~

2021-07-03 17:14 UTC, multimokia commented on Monika After Story/game/script-anniversary.rpy
> +    m 1eubsb "You know, seven is considered a lucky number in many cultures.{w=0.2}{nw}"
```suggestion
    m 1eubsb "You know, seven is considered a lucky number in many cultures.{w=0.2} {nw}"
```

2021-07-03 17:14 UTC, multimokia commented on Monika After Story/game/script-anniversary.rpy
> +    m 2ekbltpa "I know I'll be okay, though.{w=0.3} Even if I have a long way to wait, I still consider myself incredibly lucky to have met you."
```suggestion
    m 2ekbltpa "I know I'll be okay, though.{w=0.2} Even if I have a long way to wait, I still consider myself incredibly lucky to have met you."
```

2021-07-03 17:14 UTC, multimokia commented on Monika After Story/game/script-anniversary.rpy
> +    m 2dkbltpa "You're all the fortune I need, [player]."
Thinking dried tears here to phase out of them
```suggestion
    m 2dkbltda "You're all the fortune I need, [player]."
```

2023-06-10 21:41 UTC, multimokia approved these changes

2023-09-16 15:12 UTC, ThePotatoGuy approved these changes

2023-09-16 15:12 UTC, merged