Added a decorator for deprecation
Monika-After-Story/MonikaModDev pull request #7379
Opened 2021-06-23 12:55 UTC by Booplicate

Now we have a proper way to deprecate functions/classes

### Changes:
- added `mas_utils.deprecated`. Accepts 2 parameters: `use_instead` - the name of the new function to use, `should_raise` - boolean whether or not we should raise a deprecation warning.
- added the new decorator to deprecated functions and classes in our code.

### Testing:
- verify we log/raise deprecation warnings for all our deprecated functions and classes.
- **verify we don't raise exceptions for the things still in use.** I checked that, but just in case.
- verify we provide the new alternatives where it's possible (via `use_instead`).

2021-07-29 01:41 UTC, ThePotatoGuy commented
how do these end up showing up?

I checked the ghactions log and I didn't see any deprecation warnings.

2021-07-29 01:46 UTC, ThePotatoGuy requested changes

2021-07-29 01:46 UTC, ThePotatoGuy commented on Monika After Story/game/sprite-chart.rpy
> +        @store.mas_utils.deprecated()
the `wear_acs_x` replacement is `wear_acs_in` with the appropriate ACS constant.

2021-07-29 16:00 UTC, Booplicate commented
Can't seem to make it log to the gh actions log, do we need that, @ThePotatoGuy?

Right now it prints to `mas_log` and stderr (console). In case of raising a DW, gh will fail the check, so we'd see it here (see 1st commit).

2021-07-31 19:47 UTC, ThePotatoGuy commented
I see, I think it would be nice if the soft warnings were in the ghactions log, too, but if the linter doesn't trigger these automatically then its probably too much effort to be worth it.

2021-07-31 20:02 UTC, ThePotatoGuy requested changes

2021-07-31 20:02 UTC, ThePotatoGuy commented on Monika After Story/game/00utils.rpy
> +        Decorator that marks functions and classes as deprecated
can you add a comment explaining that the deprecation warnings will appear in the mas_log when the code is **executed**, and not necessarily when its compiled to bytecode?

2021-07-31 20:17 UTC, Booplicate commented
Got another idea, let's see.

2021-07-31 21:19 UTC, Booplicate commented
Weird, when I run lint locally, I see the warnings, but not on github.

2021-08-01 20:11 UTC, ThePotatoGuy approved these changes

2021-08-01 20:13 UTC, merged