Hair fixes and stuff
Monika-After-Story/MonikaModDev pull request #8007
Opened 2021-10-06 19:00 UTC by Booplicate

This contains sprite changes from #6915, so we can test/merge these quickly.

### Changes:
- removed unused assets
- updated hair sprites with a more natural color
- added `orcaramelo_bunbraid` to where it belongs to

## Steps to convert existing sprites (will be copied over to the psd wiki)
1. Export existing hair sprites to individual PNGs 
2. Open the hair sprite PNGs as layers in `new_hair_layer.xcf`
3. Export each hair sprite using the `USE AS MASK` layer as a clipping/layer mask

2021-10-06 19:09 UTC, multimokia submitted a review, later dismissed

2021-10-06 19:11 UTC, ThePotatoGuy requested changes
Couple of things:
* What is the process used to recolor existing hair sprites to match these?
* I need an original size PSD of the primary hairs (def, bun, down) to update the PSDs
* There is a change to hair down front in #7984 that should be made here. I'll probably do this later.

2021-10-18 04:50 UTC, ThePotatoGuy approved these changes

2021-10-18 04:54 UTC, multimokia approved these changes

2021-10-18 04:56 UTC, merged