Content "Eating with family good bye"
Monika-After-Story/MonikaModDev pull request #8153
Opened 2021-11-01 19:00 UTC by Alexxx1407

literally a good bye saying you go eat dinner with you're family, monika reacts differently depends on you're time.

2021-11-01 21:00 UTC, WiiBii2 commented
This looks fantastic! A few grammatical errors, but I see nothing wrong with the code itself! Keep up the good work!

2021-11-01 21:02 UTC, Alexxx1407 commented
Thanks! i mean i'm not English ... But thanks! so i need to add new things or?

2021-11-01 21:19 UTC, WiiBii2 commented
I'd run Monika's script through a web-based grammar checker like Grammarly.com just to check for issues like that. It's mostly just nit picky stuff that would sound okay if you were talking out loud, but doesn't work in writing (for instance, saying “you're” instead of “your” and using an incorrect tone).

>            m 2ekd "Are you sure you've had enough rest for it?"

This is the only dialogue that I would deem 'unreadable', but only because it is unclear. I assume you meant to ask the player if they have spent too much time with Monika and if they need a break, in which case I would just say "You should probably take a break!” Like I said though, this is  a very good first contribution, especially for someone who's first language is not English!

2021-11-01 21:20 UTC, Alexxx1407 commented
I see lemme edit it then, and thanks! i appreciate it. and beside that all good?

2021-11-01 21:26 UTC, Alexxx1407 commented
Done i edited it, all good!

2021-11-01 22:33 UTC, Alexxx1407 commented
So will you add it to the main game, or do I need to add some things again?

2021-11-01 23:52 UTC, WiiBii2 commented
I'm actually not a moderator, so I don't have the privileges to merge the request haha. However, a French translation sounds great! If you open a suggestion under issues, I'm sure the creators would love the idea! If I remember correctly, there has been plenty of talk about translating the game through Renpy's auto translator, but nothing has been done to my knowledge.

2021-11-01 23:57 UTC, Alexxx1407 commented
Alright I'll try tomorrow!! But can you try to ask if my code will be in the main game ? I'm gonna sleep bye!Sent from Android deviceLe 2 nov. 2021 00:52, WiiBii2 ***@***.***> a écrit :
I'm actually not a moderator, so I don't have the privileges to merge the request haha. However, a French translation sounds great! If you open a suggestion under issues, I'm sure the creators would love the idea! If I remember correctly, there has been plenty of talk about translating the game through Renpy's auto translator, but nothing has been done to my knowledge.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-11-02 00:42 UTC, multimokia requested changes

2021-11-02 00:42 UTC, multimokia commented on Monika After Story/game/script-farewells.rpy
> +        if session_time < datetime.timedelta(minutes=20):
```suggestion
        elif session_time < datetime.timedelta(minutes=20):
```

2021-11-02 00:42 UTC, multimokia commented on Monika After Story/game/script-farewells.rpy
> +            m 3kublu "Maybe me, ehehehehe~~"
Consistency: we only have `ehehe` or `ahaha` at those fixed lengths
```suggestion
            m 3kublu "Maybe me, ehehe~"
```

2021-11-02 00:42 UTC, multimokia commented on Monika After Story/game/script-farewells.rpy
> +        m 6lkc "I guess I'll see you after you're diner."
```suggestion
        m 6lkc "I guess I'll see you after you're dinner."
```

2021-11-02 00:42 UTC, multimokia commented
please rebase your PR. All PRs should be targetting `content`

2021-11-02 01:01 UTC, KiddTheManiac commented
I'm seeing a lot of weird grammatical errors, this might need some extra proofreading? Like the "you're dinner" and "you're family". Both of those should just be "your", I believe.

2021-11-02 01:12 UTC, Alexxx1407 commented
Don't worry guys, i will fix everything tomorrow, i need to sleep for now, good night!!Sent from Android deviceLe 2 nov. 2021 02:02, KiddTheManiac ***@***.***> a écrit :
I'm seeing a lot of weird grammatical errors, this might need some extra proofreading? Like the "you're dinner" and "you're family". Both of those should just be "your", I believe.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

2022-01-15 23:32 UTC, multimokia commented
Going to close this as it seems a little unnecessary given we already have an `I'm going to eat` farewell, this can more or less fall under that same umbrella.

2022-01-15 23:32 UTC, closed without merging