Finished Product - [Content] Extended Responses for Script-Brbs.rpy (Brb choices and return dialogue)
Monika-After-Story/MonikaModDev pull request #8155
Opened 2021-11-01 22:25 UTC by WiiBii2

Finally done after about a week of coding. This is going to be partnered with a future PR I'll open that adds variety to the responses in moods.rpy. As always, if there are any problems, feel free to leave a comment!

2021-11-01 23:05 UTC, multimokia commented
Please do not put multiple unrelated things into a single PR. It makes reviewing it infinitely more troublesome. 

Additionally, we ask that contributors please test their contributions before submitting them.

2021-11-01 23:15 UTC, multimokia requested changes

2021-11-01 23:15 UTC, multimokia commented on Monika After Story/game/script-brbs.rpy
> +                m 3hub "I'll be here when you're done!"
I don't like this approach, it's very much non-scalable and also inefficient at large scales.

I'd suggest using something like MASQuipList to use label quips as it's cleaner and simpler to expand in future

2021-11-01 23:15 UTC, multimokia commented on Monika After Story/game/script-brbs.rpy
> +            if goodbye = 1:
invalid syntax. This occurs in all checks.

2021-11-02 12:13 UTC, WiiBii2 commented
> Please do not put multiple unrelated things into a single PR. It makes reviewing it infinitely more troublesome.

I was told by Booplicate to do this way in #8080 . Here's the full quote if you would like it.

> > Would you like me to split this into topic by topic (Homework responses and then the responses with moods) or by rpy file by rpy file (full brb responses and full mood responses)?
> 
> Not as much by "rpy files", as by systems you're changing. I'd say moods go in one PR, brbs in another PR.

2021-11-02 15:36 UTC, WiiBii2 commented
@Booplicate Is there anything that you would recommend before I redo the code?

2021-11-02 15:40 UTC, multimokia commented
Basically keep all related *topics* together. Unrelated topics should be in their own PRs.

So one brb per PR pretty much. It becomes easier to manage and review vs a lot at once.

2021-11-02 15:42 UTC, Booplicate commented
Do you need to help with something specific? I agree with @multimokia. Using `MASQuipList` might be the best approach for this. I also mentioned before that you can't use single `=` for comparison. While we test every addition, you should test your code, too.

2021-11-02 15:48 UTC, Booplicate commented
You don't have to close old PRs, you can edit them.

2021-11-02 16:02 UTC, WiiBii2 commented
Okay, haha. Sorry for asking so many questions. I'll try to fix this to the best of my ability.

2021-12-23 20:05 UTC, multimokia commented
Going to close this as this is kinda unmaintainable in the current state given how large it is making it difficult to review but also doesn't quite let us easily cut things which may not work too well either.

As well, we highly recommend testing your contributions before submitting them since I can see at a glance already numerous areas which will crash due to a syntax error, this also delays the speed at which we review the contribution since we need to fix all the bugs first.

If you want to re-open in the future, please ensure it's tested, and please split things into different PRs to help make it more manageable.

2021-12-23 20:05 UTC, closed without merging