First time crash greet improvements
Monika-After-Story/MonikaModDev pull request #8278
Opened 2021-11-19 05:14 UTC by jmwall24

Improves/fixes a few things in the crash greet. 

- Currently you can quit by force closing the game at any time during this greet and there is no warning and upon next load, you get the greeting for a subsequent crash. We will now disable quit once you get past the first menu since she is sure you are there then. We also won't set `persistent._mas_crashed_before ` to True until this same point, so if you do quit before this, you still get this greet next load
- The transition from the black screen to the spaceroom with the lights on wasn't great. No matter what, we showed an empty spaceroom with no desk, and then she just dissolves in, which didn't really make sense. Now if you turn the light on, she's just there when the lights turn on, and if she turns the lights on, we start with empty desk, and then she sits down.
- We've finally added an actual light switch sfx, handling a longstanding `TODO`. File from https://www.freesoundslibrary.com/light-switch-sound-effect/ (note to @ThePotatoGuy to add a list of our free sounds)

## Testing

- verify force closing the game after the initial menu now functions as you would expect and results in an appropriate greeting upon next load
- verify force closing the game before the menu results in getting this same greet upon next load
- verify transition from the black screen is appropriate and light switch sound is good

2021-11-20 04:36 UTC, lunulae submitted a review, later dismissed

2021-11-20 12:44 UTC, Booplicate requested changes

2021-11-20 12:44 UTC, Booplicate commented on Monika After Story/game/script-story-events.rpy
> +    play sound "mod_assets/sounds/effects/light-switch-sound-effect.mp3"
I think we should define our audio files as well so it's easier to reuse that type the whole filepath to it.

2021-11-28 22:29 UTC, Legendkiller21 approved these changes

2021-11-28 22:31 UTC, Booplicate submitted a review, later dismissed

2021-12-05 20:36 UTC, ThePotatoGuy requested changes
The dialogue box that shows up when you try to close with the X button doesn't really fit with the mood. I think we if want to prevent quit after the first menu choice, we need to change the quit dialogue to fit with the crashed greet.

2021-12-23 16:48 UTC, multimokia approved these changes

2022-01-02 00:17 UTC, ThePotatoGuy commented
@jmwall24 i have added quit box APIs, please make adjustments to the quit dialogue

2022-01-08 23:27 UTC, ThePotatoGuy approved these changes

2022-01-08 23:30 UTC, multimokia approved these changes

2022-01-08 23:41 UTC, Booplicate approved these changes

2022-01-09 21:47 UTC, merged