NYE data fix
Monika-After-Story/MonikaModDev pull request #8350
Opened 2021-12-05 18:31 UTC by jmwall24

An issue arose last year due to the wrong year being used and a check that extended past the reset trigger date that allowed `mas_gone_over_nye_check` to set data for the following year. The issue itself was fixed in https://github.com/jmwall24/MonikaModDev/commit/de4eb6dc549e23ebab18f8cca03636b52b0263cc and now we are fixing the bad data by resetting `persistent._mas_nye_spent_nye` and `persistent._mas_nye_nye_date_count` and amending 2020 historical data if applicable.

## Testing

- on a persistent with historical data from 2020, set `persistent._mas_nye_spent_nye` to True and `persistent._mas_nye_nye_date_count` to any non-zero integer and then run the update script. Verify the vars are `False` and `0` respectively (defaults) and that historical data has been updated accordingly.
- on a persistent with no historical data from 2020 (fresh persist is easiest) repeat the above test. Verify both vars are now defaulted, history has not been touched, and there were no crashes.

2021-12-05 20:22 UTC, ThePotatoGuy requested changes

2021-12-05 20:22 UTC, ThePotatoGuy commented on Monika After Story/game/updates.rpy
> +        local_now = mas_utils.utc_to_local(datetime.datetime.utcnow())
```suggestion
        local_now = datetime.datetime.now()
```

utc APIs are for converting existing times, can just use regular now for local now

2021-12-05 20:36 UTC, ThePotatoGuy approved these changes

2021-12-07 18:26 UTC, Legendkiller21 approved these changes

2021-12-08 03:15 UTC, merged