Add test topic for `register_img_same`
Monika-After-Story/MonikaModDev pull request #8393
Opened 2021-12-12 06:42 UTC by ThePotatoGuy

@multimokia , I didn't find any issues using `register_img_same`. Let me know if you can recreate the issue.

# Key Changes
* Adds a testing topic `DECO TAG TEST API REG SAME` for checking the `register_img_same` function.

# Testing
* run the `DECO TAG TEST API REG SAME` dev topic - verify that the blue deco remains in the same place for each background.

2021-12-23 18:12 UTC, multimokia requested changes
Figured the issue out. It's an issue with init order. We should **never** use `register_img_same` on the same init level as `register_img` for the original, because it will always fail provided the tag does not exist yet. 

As such:
It might be worth just raising an error or logging in place of silently handling the issue as to actually provide some feedback to the user. Requesting some changes to add logging or an ex throw for it if config.developer

2022-01-02 06:26 UTC, ThePotatoGuy commented
@multimokia I added an exception

2022-01-02 16:19 UTC, multimokia approved these changes

2022-01-16 16:43 UTC, Legendkiller21 approved these changes

2022-01-16 16:52 UTC, merged