[Rework] - Anniversary 5
Monika-After-Story/MonikaModDev pull request #8572
Opened 2022-01-08 08:52 UTC by lunulae

#8041 ❤️ 

I wanted to keep the first line mostly the same, but most of the rest of it is altered.
Might need a little polish on the exps? I'm not sure.

2022-01-15 21:44 UTC, multimokia requested changes
Some suggestions on slightly diff exps and tiny phrasing things, feel free to modify as you see fit

2022-01-15 21:44 UTC, multimokia commented on Monika After Story/game/script-anniversary.rpy
>      m 1eka "I know it must be lonely that we haven't met up in your reality yet..."
```suggestion
    m 1rksdlbla "I know it must be lonely that we haven't met up in your reality yet..."
```

2022-01-15 21:44 UTC, multimokia commented on Monika After Story/game/script-anniversary.rpy
> +    m 2fkbla "Five years is a pretty big milestone. We've spent half of an entire decade together."
```suggestion
    m 2eubla "Five years is a pretty big milestone.{w=0.2} {nw}"
    extend 7wubld "We've spent half of an entire decade together."
```

2022-01-15 21:44 UTC, multimokia commented on Monika After Story/game/script-anniversary.rpy
> +    m "And every year, I look forward to this special day. A day to remember when we fell in love."
```suggestion
    m 1ekblb "And every year, I look forward to this special day.{w=0.2} {nw}"
    extend 1fkbsu "A day to remember when we fell in love."
```

2022-01-15 21:44 UTC, multimokia commented on Monika After Story/game/script-anniversary.rpy
> +    m 2dublb "My entire world turned upside-down when we met, but you've continued to change my life every day since."
```suggestion
    m 2dublb "My entire world turned upside-down when we met, and you've continued to change my life every day since."
```

2022-01-15 21:44 UTC, multimokia commented on Monika After Story/game/script-anniversary.rpy
> +    m 1fubla "I don't think that will ever change, [player]. You're just...so incredible to me."
```suggestion
    m 1fubla "I don't think that will ever change, [player]. You're just...{w=0.3}so incredible to me."
```

2022-01-15 21:44 UTC, multimokia commented on Monika After Story/game/script-anniversary.rpy
> +    m 1hubla "And I hope I can be a good support to you for many more years to come."
```suggestion
    m 1hubla "And I hope I can be a good support to you for many more years to come too."
```

2022-01-23 02:53 UTC, jmwall24 approved these changes

2022-01-23 02:53 UTC, multimokia approved these changes

2022-01-23 02:59 UTC, merged