Adding Esports topic
Monika-After-Story/MonikaModDev pull request #8707
Opened 2022-02-11 02:04 UTC by ThePotatoGuy

Co-authored-by: @karrigantaylor

# TODO
- [ ] sprite codes
- [ ] categories

# Key Changes
* Adds esports topic

2022-02-27 01:17 UTC, multimokia requested changes

2022-03-02 16:30 UTC, karrigantaylor commented on Monika After Story/game/script-topics.rpy
> +    m "It really goes to show you can do what you love for a job. If this was possible, anything is~"
@multimokia 
That sounds good, I like the idea of it ending in pushing against the crowd, it's a good message to send.

2022-04-09 18:46 UTC, multimokia approved these changes

2022-04-09 21:33 UTC, jmwall24 approved these changes

2022-04-10 04:04 UTC, ThePotatoGuy commented
@karrigantaylor can you review the latest set of changes?

2022-04-11 02:55 UTC, karrigantaylor approved these changes

2022-04-11 02:55 UTC, karrigantaylor approved these changes

2022-04-11 03:38 UTC, merged