Add scary story "Prison escape"
Monika-After-Story/MonikaModDev pull request #8768
Opened 2022-02-20 04:52 UTC by Mosexelle

New scary story "Prison escape".
This is not my story, if I'm not mistaken it's Alfred Hitchcock. It's pretty short and scary, but it's a good fit for a storyteller like Monika.

2022-09-13 22:33 UTC, my-otter-self reviewed
2 extend fixes, adding pauses and nws.

2022-09-13 22:33 UTC, my-otter-self commented on Monika After Story/game/script-stories.rpy
> +    m "Finally she heard the dirt dropping onto the top of the wooden coffin"
`    m "Finally she heard the dirt dropping onto the top of the wooden coffin{w=0.1}{nw}"`

2022-09-13 22:33 UTC, my-otter-self commented on Monika After Story/game/script-stories.rpy
> +    m "Quietly in the dark, she found the coffin that contained the dead body"
`    m "Quietly in the dark, she found the coffin that contained the dead body{w=0.1}{nw}"`

2022-10-22 22:41 UTC, multimokia requested changes
smol indent mismatch

2022-10-22 22:41 UTC, multimokia commented on Monika After Story/game/script-stories.rpy
> +    code="STY"
```suggestion
        code="STY"
```

2022-10-22 22:43 UTC, jmwall24 approved these changes

2022-10-22 22:45 UTC, multimokia approved these changes

2022-10-22 22:46 UTC, merged