Cleanup pronouns
Monika-After-Story/MonikaModDev pull request #8996
Opened 2022-03-21 13:54 UTC by Booplicate

### Changes:
- the map is global now
- don't duplicate the keys anymore (I think this way it's cleaner, but I can revert that change)
- use `setattr` to dynamically add new words from the map (easier to maintain)
- `mas_set_gender` is deprecated, we don't set gender, we set pronouns. Now the old label jumps to the new - `mas_set_pronouns`
- `mas_set_pronouns` accepts the `gender` param, by default `None`. if `None`, uses the gender value from the persistent, otherwise uses the given value to set the pronouns.

2022-03-22 04:11 UTC, ThePotatoGuy requested changes
can you make the prounoun setting a function (prob ch30 api) and just have the label call that?

2022-03-22 14:17 UTC, Booplicate commented
This should do

2022-03-28 01:36 UTC, ThePotatoGuy requested changes

2022-03-28 01:36 UTC, ThePotatoGuy commented on Monika After Story/game/dev/dev_unittest.rpy
> +            pronouns_tester.assertTrue("X" in sub_map)
these are checking if the sub map is the same length as other maps, and the main 3 gender types have an entry in the sub map, correct? to make it easier for debugging, we should have a prepare test line for the size check, and then a prepare test line before the gender types checks. Can use the pronoun (key) in the prepare test text as well. That way when Monika says a test failed, it won't always be "Validate map size and keys" when only one part of the map has an issue.

2022-03-28 01:36 UTC, ThePotatoGuy commented on Monika After Story/game/dev/dev_unittest.rpy
> +                pronouns_tester.assertEqual(global_value, map_value)
same thing I said above.

2022-04-09 18:37 UTC, ThePotatoGuy approved these changes

2022-05-24 16:32 UTC, Legendkiller21 approved these changes

2022-05-24 22:18 UTC, ThePotatoGuy approved these changes

2022-05-24 22:18 UTC, merged