[New Outfit] Button Up (Flowered)
Monika-After-Story/MonikaModDev pull request #9172
Opened 2022-05-23 21:56 UTC by kkrosie123

It just needs thumbs

2022-05-28 21:56 UTC, ThePotatoGuy requested changes

2022-05-28 21:56 UTC, ThePotatoGuy commented on spritepacks/released/briaryoung/briaryoung-button-up-flowered/mod_assets/monika/j/briaryoung_clothes_button_up_flowered.json
> +        "bare-shoulders": true,
this outfit does not actually have bare shoulders, so I don't think this should have this exprop. Is this here for hair compatibility purposes?

2022-05-30 06:43 UTC, lunulae submitted a review, later dismissed
Tested, all the poses look good to me! If there are no other issues with the .json I think it's ready to merge.

2022-05-30 20:29 UTC, lunulae approved these changes

2022-05-30 23:26 UTC, ThePotatoGuy approved these changes

2022-05-30 23:26 UTC, merged