[Chess Involve] Simply a in-game chess mode description
Monika-After-Story/MonikaModDev pull request #9456
Opened 2022-08-19 10:21 UTC by Wingdinggaster656

Introduce a mode description dialogue, so players know what these modes do.

Tested, no any obvious bug, though not sure if the choice menu looks cool and good.

2022-08-19 16:25 UTC, Booplicate requested changes

2022-08-19 16:25 UTC, Booplicate commented on Monika After Story/game/chess.rpy
> +                m 1eub "In this way, heavy opening theory can be avoided, and the real test of the player's understanding of chess is coming."
Can you compress this to also take 1-3 short lines? I feel like there's too much information (who made it and why it's called 960).

2022-08-19 16:25 UTC, Booplicate commented on Monika After Story/game/chess.rpy
> +            if _return is 0:
Don't use `is` with literals. Also probably make it a string constant like the rest, for example, `"explain_rules"`.

2022-08-19 17:03 UTC, Wingdinggaster656 commented
Switched to `"explain_modes"` and compressed the dialogue a little. Maybe need to compress more.

I think, however, that this dialogue is more of a one-off (the player sees it once and remembers it), and as a one-off topic, a longer dialogue might be suitable.

2022-09-04 21:30 UTC, jmwall24 approved these changes

2022-09-04 21:38 UTC, Booplicate approved these changes

2022-09-04 21:58 UTC, merged