[contributing] [mod] panicking mood.
Monika-After-Story/MonikaModDev pull request #9517
Opened 2022-09-11 16:42 UTC by my-otter-self

adds a new mood, the "i feel like panicking."

2022-09-11 20:05 UTC, Rai99 commented on Monika After Story/game/script-moods.rpy
> +    m 5fkbsa "But for now, know that I love you and that everything is going to be okay."
Dissolve into body pose 5
```suggestion
    show monika 5fkbsa at t11 zorder MAS_MONIKA_Z with dissolve_monika
    m 5fkbsa "But for now, know that I love you and that everything is going to be okay."
```

2022-09-11 20:59 UTC, dreamscached commented on Monika After Story/game/script-moods.rpy
> +    m 7ekb "Do you feel better, [mas_get_player_nickname()]? "
```suggestion
    m 7ekb "Do you feel better, [mas_get_player_nickname()]?{w=0.3}{nw} "
```

2022-09-13 13:19 UTC, Wingdinggaster656 requested changes

2022-09-13 13:19 UTC, Wingdinggaster656 commented on Monika After Story/game/script-moods.rpy
> +    m "And out.{w=1.0}.{w=1.0}.{w=1.0}.{w=1.0}.{w=1.0}."
```
    m 2dud "Breathe in.{w=1.0}.{w=1.0}.{w=1.0}."
    m "And out.{w=0.1}.{w=1.0}.{w=1.0}.{w=1.0}.{w=1.0}."
    m 2fua "Let's do it one more time."
    m 2dud "Breathe in.{w=1.0}.{w=1.0}.{w=1.0}."
    m "And out.{w=1.0}.{w=1.0}.{w=1.0}.{w=1.0}.{w=1.0}."
```

Personally, I think these lines should end with `{nw}`, so players can focus on taking a deep breath without clicking.

2022-11-29 18:37 UTC, closed without merging